---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: devonm/netbox-docker-saml:${{ github.event.inputs.from_tag || env.DEFAULT_FROM_TAG }}
          push: ${{ github.event_name == 'push' }}
          build-args: FROM_TAG=${{ github.event.inputs.from_tag || env.DEFAULT_FROM_TAG }}
        env:
          DEFAULT_FROM_TAG: latest
