---
name: build

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      from_tag:
        description: "netboxcommunity/netbox tag to use"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          tags: devonm/netbox-docker-saml:${{ github.event.inputs.from_tag }}
          push: ${{ github.event_name == 'workflow_dispatch' }}
          build-args: FROM_TAG=${{ github.event.inputs.from_tag || 'latest' }}
