---
name: build

on:
  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      from_tag:
        description: "netboxcommunity/netbox tag to use"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: Dockerfile
          repository: devonm/netbox-docker-saml
          tags: ${{ github.event.inputs.from_tag }}
          build_args: FROM_TAG=${{ github.event.inputs.from_tag || 'latest' }}
